### ISSUE TITLE
Complete Inspection Improvements

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#16]
My second question has to do with the last step of completing an inspection. If you look at the above screenshot you will see that the Repair Category and Repair Code are not only required fields but also have a drop down option. Can we either hard code these fields where techs will not have access to change the fields or maybe hide these two fields altogether? All inspections should be “Inspections” for repair category and “Inspection completed” for the repair code (my screenshot has Inspection passed selected – please disregard).

Also, for the comments field I think it would be best if we can make this field also optional like the other comment fields in the app. Is that an option?

**Comment by SamOrozco** [comment]
Completed in beta
