### ISSUE TITLE
Enhancement - Linkable Asset/Equipment Attribute Data on Inspections

### ISSUE THREAD

**Issue by jam412ep** [apptreesoftware/corrigo-issues#18]
On Inspection WO view.  Allow a clickable link to drill down into an Assets Attributes.  Will be important for inspector to be able to view attribute data for a particular asset.
![image](https://cloud.githubusercontent.com/assets/24575560/21201286/0ac0c190-c210-11e6-9834-8acddf34332d.png)

**Comment by matthewtsmith** [comment]
@jam412ep @alexisandreason We can do this as a SingleRelationship to allow the user to drill into the Asset Detail. Currently the 9.x Corrigo services has limited asset information so we'll have to see what is available to us.

**Comment by matthewtsmith** [comment]
- [ ] Change To Do to `Inspection Items`
- [ ] move To Do items to the top
- [ ] To Do list should have the last part of the task name in the repeating element
- [ ] Tapping on the To Do Item should take you to a child form with the asset and task detail for that item.

**Comment by matthewtsmith** [comment]
@jam412ep This is now deployed. Please verify it meets your expectations.
