### ISSUE TITLE
Add area for "completed inspections"

### ISSUE THREAD

**Issue by DmitriyChernikov** [apptreesoftware/corrigo-issues#19]
Enhancement: Could you add a section where completed inspections can be pulled up? As of now once complete the inspection is no longer available in the application.

**Comment by SamOrozco** [comment]
Do we want to only display completed Work Orders for Logged in user? Do we want to limit this to a date range or do we want to give them the option to limit this by a date range

**Comment by DmitriyChernikov** [comment]
For now they should display only complete Work Orders that were assigned to the logged in user. 

We would want the range to be past 90 days. We would need a search function where you could search for a completed work order by the work order number. Ideally the search function will pull up any work order with that work order number (not limited to just 90 days).

**Comment by matthewtsmith** [comment]
@DmitriyChernikov We will set this to 90 days but we'll make it configurable via the builder. We are also adding a search form. Both of those should be in the app by tomorrow or Monday.
