### ISSUE TITLE
Create demo environment for Corrigo

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#23]

**Comment by matthewtsmith** [comment]
Make the app ID demo.corrigo.com. 

It should include all available functionality we have.

**Comment by alexisandreason** [comment]
@matthewtsmith As per your request yesterday, the Baptist Health app has been copied to demo.corrigo.com with only the inspection features.

**Comment by matthewtsmith** [comment]
@alexisandreason Don't bother assigning back to me. Just close a ticket if its live.
