### ISSUE TITLE
Error message when Starting a WO: "Submission Failed" 

### ISSUE THREAD

**Issue by farhan755** [apptreesoftware/corrigo-issues#25]
I am receiving this error message (img below) as I am trying to start any of the WO from my inspection list. Error Msg: "Submission Failed: Data was already modified by another user" 

iPhone, testing time: 3:20pm central

![image](https://cloud.githubusercontent.com/assets/24660186/21329585/0b481fb2-c5ff-11e6-90b1-24652549b955.png)

**Comment by farhan755** [comment]
And sorry... I don't know how to add the darn labels... 

label: Bug, iPhone,

**Comment by SamOrozco** [comment]
This is fixed and pull request waiting to be approved.

**Comment by SamOrozco** [comment]
This was due to the connector trying to assign an employee for the parent Inspection who already had an employee assigned to it. When updating work orders the connector checks to make sure that it's not re-assigning for the parent work order.
