### ISSUE TITLE
Issue with Punch Lists

### ISSUE THREAD

**Issue by farhan755** [apptreesoftware/corrigo-issues#30]
I’m running into a small issue with the Punch Lists. Here is how I have the Punch List set up for "Daily Central Plant Inspection - Chiller/AHU": 

 
![image](https://cloud.githubusercontent.com/assets/24660186/21895415/4719b6fc-d8a8-11e6-9d6f-0a949c26d7a2.png)

And here is how I have the exception “STAT” set up, to give me the exception choices ON, OFF, and STANDBY

 
![image](https://cloud.githubusercontent.com/assets/24660186/21895433/573796c6-d8a8-11e6-9aa7-f787cc6b8978.png)

I then generated a WO using this punch list (SMMAB15428) and in AppTree I see “Pass” and “Fail” as selectable for the first 4 punch list questions when I did not specify any exception choice. And I see no choice for the Status question when I included STAT for my choice options. 

 
![image](https://cloud.githubusercontent.com/assets/24660186/21895391/2bd3fd6c-d8a8-11e6-8484-6c39ef763d1d.png)

 
![image](https://cloud.githubusercontent.com/assets/24660186/21895383/281929f4-d8a8-11e6-9cdc-8f61fee2a3ce.png)

**Comment by matthewtsmith** [comment]
@SamOrozco This may just be a caching issue. Lets set the cache interval for the PunchList Exceptions to 5 minutes and see if it starts showing up.
