### ISSUE TITLE
Completed inspections need to remain on the app for the techs to see for a month

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#31]
Update query to show Completed inspections for 1 month. This should be a parameter passed into the service and defined in the builder.

**Comment by SamOrozco** [comment]
This functionality is already in place. It was set for 90 days, but I changed to 30.

**Comment by SamOrozco** [comment]
This is already in production the value just needs to be set in the portal server parameters.
