### ISSUE TITLE
Create new environment ‘Test Preview BHE’

### ISSUE THREAD

**Issue by RobertGuinn** [apptreesoftware/corrigo-issues#36]
‘Test Preview BHE’, use same credentials.

**Comment by RobertGuinn** [comment]
@SamOrozco set this up by COB Friday 2/3 and notify danielal@corrigo.com

**Comment by SamOrozco** [comment]
@RobertGuinn Is there a new environment URL I'm pointing this to? or are they just wanting a new app pointed to preview baptist health.

**Comment by RobertGuinn** [comment]
@SamOrozco I believe this is a new environment.  You would: create app id under the Corrigo brand, register the connector to the new environment and QA it.

**Comment by RobertGuinn** [comment]
@SamOrozco update the ticket with the status.

**Comment by SamOrozco** [comment]
The new test environment has been created, pointing the preview-baptisthealth.corrigo.com appID to the `Test Preview BHE` environment.

**Comment by RobertGuinn** [comment]
@SamOrozco customer notified?

**Comment by SamOrozco** [comment]
Yes they have.
