### ISSUE TITLE
Not receiving assigned Inspection WOs in AppTree

### ISSUE THREAD

**Issue by farhan755** [apptreesoftware/corrigo-issues#38]
Examples: 

SMMAB15627
SMMAB15628
SMMAB15630
SMMAB15631 

These Inspection-Type WOs were created in Preview Baptist Health. They were assigned to me (FarhanR) but they are not showing up in the AppTree mobile app.

**Comment by matthewtsmith** [comment]
@SamOrozco this is because we updated this app to point to Test BHE. We are no longer receiving data from the old environment. Work with @farhan755 to see if they need both environments. If so create a new app if for the Test BHE

**Comment by RobertGuinn** [comment]
@SamOrozco did you work on this issue?

**Comment by SamOrozco** [comment]
@farhan755 
For the `Preview Baptist Health` environment you will use the `preview-baptisthealth.corrigo.com` AppID as usual 

For the `Preview Test BHE` environment you will need to use the `preview-test-bhe.corrigo.com` AppID

**Comment by farhan755** [comment]
Thank you! It’s working

Farhan Rahman |  Project Manager – Client Implementations  |  Corrigo a JLL company
farhanr@corrigo.com | 972-256-6869 | www.corrigo.com<http://www.corrigo.com/>

[cid:image001.png@01D22085.1D9D6840]<http://www.corrigo.com/connect-conference/>

**Comment by Zboatman** [comment]
Hi Sam,
We gave you the wrong information around the second site it should be:

test-preview-bhe.corrigo.com

Can you redirect to the right site?
