### ISSUE TITLE
Add ability to update a Work Order Status

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#4]
Corrigo has fairly strict status rules.

1. A work order in `New` state must be `Picked up` using the WoPickupCommand. This moves it into the `Open` state.

2. From the `Open` state the user can `Start` or `Pause` it moving it into the `Open: In Progress` or `Open: Paused` respectively. You must use the dedicated WoActionCommand to accomplish these.

3. A user can move it into the `On Hold` State.

4. Lastly, a user can Close a work order. You must use the WoCloseCommand to accomplish this.

**Comment by alexisandreason** [comment]
@matthewtsmith This has been completed in the Baptist Health beta app.
