### ISSUE TITLE
WorkOrder - Add Note

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#5]
Corrigo has the ability to add a note to a work order. This should be possible on the Work Order Detail page using the WorkOrderData Source. The note should be a Relationship and show on the form as a repeating element.

**Comment by alexisandreason** [comment]
@matthewtsmith This was working yesterday in inspect2.corrigo.com but now I am getting a weird error in the client. I am not able to see any of the fields when I click on the plus button to add a note. If I click on an existing note then I see the body and note type fields as I expect. Should I make a separate ticket for that?

**Comment by alexisandreason** [comment]
@matthewtsmith This has been finished in preview-baptisthealth.corrigo.com beta.
