### ISSUE TITLE
Add Complete Work Order capability

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#7]
We need to add the ability to close a work order form the WO Detail screen. The user should have a toolbar button to "Complete". This should bring them to a close work order view where they enter:

Repair Code
Equipment Worked on
Note

And press Close. This should change the state of the work order to completed.

**Comment by alexisandreason** [comment]
@matthewtsmith This has been completed in the Baptist Health Beta App
