### ISSUE TITLE
Add Flag work order support

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#8]
In the Corrigo Mobile app and the web application, the user has the ability to `Flag` a work order. This takes them to a list of flag options where they select an option and enter a note. We shoud add this ability to the connector so it can be configured in AppTree.

![image](https://cloud.githubusercontent.com/assets/9000800/21192846/c7cf62b4-c1de-11e6-9da6-d5511b7b4ba5.png)

**Comment by alexisandreason** [comment]
@matthewtsmith This has been implemented in the Baptist Health app in beta
